# Generated by Django 2.1.7 on 2019-03-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='userID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='userID',
            field=models.IntegerField(default=0),
        ),
    ]
