# Generated by Django 2.1.7 on 2019-03-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190324_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
        migrations.AlterField(
            model_name='question',
            name='deadline_time',
            field=models.DateTimeField(verbose_name='decision deadline'),
        ),
        migrations.AlterField(
            model_name='question',
            name='eating_time',
            field=models.DateTimeField(verbose_name='eating time'),
        ),
    ]
